.PHONY: download_data download_description

download_data:
	# command to download forestfires.csv
	# https://archive.ics.uci.edu/ml/machine-learning-databases/forest-fires/forestfires.csv

download_description:
	# command to download forestfires.names
	# https://archive.ics.uci.edu/ml/machine-learning-databases/forest-fires/forestfires.names

download_all:
	make download_data
	make download_description